spring:
  jwt:
    secret: "lovebugpacksubin1207areyoujokingme"

  datasource:
    url: jdbc:mysql://connected.cpga00emqnt0.ap-northeast-2.rds.amazonaws.com:3306/connected?createDatabaseIfNotExist=true&useSSL=false
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect